name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  package:
    description: Package name; e.g. backend, frontend
    required: true

  ### Typical / recommended
  build_context:
    description: Build context, not required for self-contained package/default directory
  build_file:
    description: Dockerfile with path, not required for self-contained package/default directory
  keep_versions:
    description: Number of versions to keep; omit to skip
  tag_fallback:
    description: Where to pull default images from; e.g. prod, test
  tags:
    default: ${{ github.event.number }}
    description: |
      Default tag(s); e.g. pr#, test, prod.
      Supports multiline input for multiple tags.
      Example: |
        pr123
        demo
        test
  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)

  ### Usually a bad idea / not recommended
  build_args:
    description: A list of build-time variables, generally not advisable
    value: "BUILDKIT_INLINE_CACHE=1"
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}
  keep_regex:
    description: Regex for tags to ignore (not delete); defaults to prod, test and semvers
    default: '^(prod|test|(v(\d+)(\.\d+){0,2}.*))$'
  repository:
    description: Non-default repo to clone
    default: ${{ github.repository }}
  tag:
    description: Deprecated input; use tags instead
    deprecationMessage: "Input 'tag' is deprecated and will be removed in a future release. Please use 'tags' instead."
  token:
    description: Specify token (GH or PAT), instead of inheriting one from the calling workflow
    default: ${{ github.token }}

outputs:
  digest:
    description: 'Digest of the built image; e.g. sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef'
    value: ${{ steps.build_and_push.outputs.digest }}

  triggered:
    description: Did a deployment trigger?  [true|false]
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    # Cleanup if inputs.keep_versions provided
    - name: GHCR Cleanup
      if: inputs.keep_versions
      continue-on-error: true # Stop fail if no versions to delete
      uses: actions/delete-package-versions@v5.0.0
      with:
        package-name: "${{ github.event.repository.name }}/${{ inputs.package }}"
        package-type: "container"
        min-versions-to-keep: ${{ inputs.keep_versions }}
        ignore-versions: "${{ inputs.keep_regex }}"

    - id: vars
      shell: bash
      env:
        INPUT_BUILD_CONTEXT: ${{ inputs.build_context }}
        INPUT_BUILD_FILE: ${{ inputs.build_file }}
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_TAGS: ${{ inputs.tags }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Process inputs and set variables
        set -euo pipefail  # Robust error handling for all script steps

        # Early exit for deprecated input
        if [ -n "${{ inputs.tag }}" ]; then
          echo "Input 'tag' is deprecated. Please use 'tags' instead."
          exit 1
        fi

        # Set build context and file with defaults
        build_context="${INPUT_BUILD_CONTEXT:-$INPUT_PACKAGE}"
        build_file="${INPUT_BUILD_FILE:-${build_context}/Dockerfile}"

        # Process tags into comma-separated list of full image paths (concise version)
        mapfile -t tags < <(printf '%s\n' "$INPUT_TAGS" | tr '[:upper:]' '[:lower:]' | tr -d ' ' | grep -v '^$')
        tags=("${tags[@]/#/ghcr.io/${GITHUB_REPOSITORY}/${INPUT_PACKAGE}:}")
        tags_csv=$(IFS=, ; echo "${tags[*]}")

        # Output all variables at once, and verify they are set
        for v in build_context build_file tags_csv; do
          if [ -z "${!v}" ]; then
            echo "Error: $v is not set!" >&2
            exit 1
          fi
          echo "$v=${!v}" >> $GITHUB_OUTPUT
        done

    # Send triggers to diff action
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ inputs.triggers }}
        diff_branch: ${{ inputs.diff_branch }}

    # Check if a build is required (steps.build.outputs.triggered=true|false)
    - name: Check for builds
      env:
        URL_FALLBACK: ghcr.io/${{ inputs.repository }}/${{ inputs.package }}:${{ inputs.tag_fallback }}
      id: build
      shell: bash
      run: |
        # Check for builds
        echo "triggered=true" >> $GITHUB_OUTPUT
        if [ "${{ steps.diff.outputs.triggered }}" == "true" ]; then
          echo "Build triggered. Used bcgov/action-diff-triggers."
        elif [ "${{ inputs.repository }}" != "${{ github.repository }}" ]; then
          echo "Build triggered.  Override repository provided."
        elif [ -z "${{ inputs.tag_fallback }}" ]; then
          echo "Build triggered.  No tag_fallback provided."
        elif [[ ! $(docker manifest inspect "${URL_FALLBACK}") ]]; then
          echo "Build triggered.  Fallback tag (tag_fallback) not usable."
        else
          echo "Container build not required"
          echo "triggered=false" >> $GITHUB_OUTPUT
        fi

    # If a build is not required, reuse a previous image
    - name: Recycle/retag Previous Images
      uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa # v4
      if: steps.build.outputs.triggered != 'true'
      with:
        registry: ghcr.io
        repository: ${{ inputs.repository }}/${{ inputs.package }}
        target: ${{ inputs.tag_fallback }}
        tags: |
          ${{ inputs.tags }}

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}

    - name: Add build envars to Dockerfile
      if: steps.build.outputs.triggered == 'true'
      env:
        dockerfile: ${{ steps.vars.outputs.build_file }}
        BUILDER_TAGS: ${{ steps.vars.outputs.tags_csv }}
      shell: bash
      run: |
        # Add build envars to Dockerfile
        set -euo pipefail

        # Diagnostics and validation for Dockerfile path
        echo "[DIAG] Checking Dockerfile path: $dockerfile"
        if [ -z "$dockerfile" ]; then
          echo "[DIAG] dockerfile is not set!" >&2
          exit 1
        fi
        if [ ! -e "$dockerfile" ]; then
          echo "[DIAG] Dockerfile does not exist at $dockerfile" >&2
          ls -l "$(dirname \"$dockerfile\")" || echo "[DIAG] Directory does not exist: $(dirname \"$dockerfile\")" >&2
          exit 1
        fi
        if [ ! -w "$dockerfile" ]; then
          echo "[DIAG] Dockerfile is not writable at $dockerfile" >&2
          ls -l "$dockerfile" || true
          exit 1
        fi
        # Add build envars to Dockerfile (pad for missing line endings!)
        echo "" >> "$dockerfile"
        echo "ENV BUILDER_IMAGE=ghcr.io/${{ github.repository }}/${{ inputs.package }}" >> "$dockerfile"
        echo "ENV BUILDER_PACKAGE=${{ inputs.package }}" >> "$dockerfile"
        echo "ENV BUILDER_REPO=${{ github.repository }}" >> "$dockerfile"
        # Use processed tags for BUILDER_TAGS
        echo "ENV BUILDER_TAGS=\"$BUILDER_TAGS\"" >> "$dockerfile"
        # Output variables for clarity
        echo "# BUILDER_TAGS: $BUILDER_TAGS"

    - name: Set up Docker Buildx
      if: steps.build.outputs.triggered == 'true'
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

    - name: Log in to the Container registry
      if: steps.build.outputs.triggered == 'true'
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }} 

    - name: Build and push ${{ inputs.package }} Docker image
      id: build_and_push
      if: steps.build.outputs.triggered == 'true'
      uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
      with:
        context: ${{ steps.vars.outputs.build_context }}
        file: ${{ steps.vars.outputs.build_file }}
        push: true
        tags: ${{ steps.vars.outputs.tags_csv }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build_args }}

    # Action repo needs to be present for cleanup/tests
    - name: Checkout local repo to make sure action.yml is present
      if: github.repository != inputs.repository
      uses: actions/checkout@v4

    # Get the digest of the built image from the build-push-action output
    - name: Validate digest
      env:
        IMAGE: ghcr.io/${{ github.repository }}/${{ inputs.package }}@${{ steps.build_and_push.outputs.digest }}
      id: digest
      if: steps.build.outputs.triggered == 'true'
      shell: bash
      run: |
        # Validate digest
        set -euo pipefail

        if ! docker pull "$IMAGE"; then
          echo "Error: Failed to pull $IMAGE" >&2
          exit 1
        fi

    - name: Print summary outputs
      shell: bash
      run: |
        echo "digest: ${{ steps.build_and_push.outputs.digest }}"
        echo "triggered: ${{ steps.diff.outputs.triggered }}"
        echo "tags_csv: ${{ steps.vars.outputs.tags_csv }}"
        # Print tags with indentation for multiline values
        echo "tags:"
        while IFS= read -r line; do
          echo "  $line"
        done <<< "${{ inputs.tags }}"
