name: Conditional Container Builder with Fallback
description: Build if trigger conditions are met, else use fallback image
branding:
  icon: package
  color: blue

inputs:
  ### Required
  package:
    description: Package name; e.g. backend, frontend
    required: true

  ### Typical / recommended
  build_context:
    description: Build context, not required for self-contained package/default directory
  build_file:
    description: Dockerfile with path, not required for self-contained package/default directory
  sbom:
    default: "true"
    description: Generate a Software Bill of Materials (SBOM) for the container image. Enabled by default for better security practices.
  keep_versions:
    description: Number of versions to keep; omit to skip
  tag_fallback:
    description: Where to pull default images from; e.g. prod, test
  tags:
    default: ${{ github.event.number }}
    description: |
      Default tag(s); e.g. pr#, test, prod.
      Supports multiline input for multiple tags.
      Example: |
        pr123
        demo
        test
  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/' './frontend/)

  ### Usually a bad idea / not recommended
  build_args:
    description: A list of build-time variables, generally not advisable
    default: "BUILDKIT_INLINE_CACHE=1"
  diff_branch:
    description: Branch to diff against
    default: ${{ github.event.repository.default_branch }}
  keep_regex:
    description: Regex for tags to ignore (not delete); defaults to prod, test and semvers
    default: '^(prod|test|(v(\d+)(\.\d+){0,2}.*))$'
  repository:
    description: Non-default repo to clone
    default: ${{ github.repository }}
  tag:
    description: Deprecated input; use tags instead
    deprecationMessage: "Input 'tag' is deprecated and will be removed in a future release. Please use 'tags' instead."
  token:
    description: Specify token (GH or PAT), instead of inheriting one from the calling workflow
    default: ${{ github.token }}
  secrets:
    description: |
      Multiline input for secrets to mount.
      https://docs.docker.com/build/ci/github-actions/secrets/#secret-mounts
      Example: |
        MY_SECRET=secret_value
        ANOTHER_SECRET=another_value

outputs:
  digest:
    description: "Digest of the built image; e.g. sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
    value: ${{ steps.build_and_push.outputs.digest }}

  triggered:
    description: Did a deployment trigger?  [true|false]
    value: ${{ steps.diff.outputs.triggered }}

runs:
  using: composite
  steps:
    - id: vars
      shell: bash
      env:
        INPUT_PACKAGE: ${{ inputs.package }}
        CONTEXT_REPO: ${{ github.event.repository.name }}
      run: |
        # Process inputs and set variables
        set -euo pipefail

        # Early exit for deprecated input
        if [ -n "${{ inputs.tag }}" ]; then
          echo "Input 'tag' is deprecated. Please use 'tags' instead."
          exit 1
        fi

        # If package matches repo name, use simpler image_path
        if [ "${INPUT_PACKAGE,,}" = "${CONTEXT_REPO,,}" ]; then
          image_path="${{ github.repository }}"
        else
          image_path="${{ github.repository }}/${{ inputs.package }}"
        fi
        echo "image_path=${image_path,,}" >> $GITHUB_OUTPUT

        # Convert multiline tags to metadata-action format (type=raw,value=tag)
        # Each line becomes: type=raw,value=<tag>
        metadata_tags=$(echo "${{ inputs.tags }}" | grep -v '^$' | tr '[:upper:]' '[:lower:]' | sed 's/^/type=raw,value=/')
        echo "metadata_tags<<EOF" >> $GITHUB_OUTPUT
        echo "$metadata_tags" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Extract first tag for artifact naming (sanitized for artifact name compatibility)
        # Artifact names can contain: letters, numbers, hyphens, underscores, and periods
        first_tag=$(echo "${{ inputs.tags }}" | grep -v '^$' | head -n 1 | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._-')
        # Fallback to 'artifact' if sanitized tag is empty
        first_tag="${first_tag:-artifact}"
        echo "first_tag=${first_tag}" >> $GITHUB_OUTPUT

    # Cleanup if inputs.keep_versions provided
    - name: GHCR Cleanup
      if: inputs.keep_versions
      continue-on-error: true # Stop fail if no versions to delete
      uses: actions/delete-package-versions@v5.0.0
      with:
        package-name: "${{ steps.vars.outputs.image_path }}"
        package-type: "container"
        min-versions-to-keep: ${{ inputs.keep_versions }}
        ignore-versions: "${{ inputs.keep_regex }}"

    # Send triggers to diff action
    - id: diff
      uses: bcgov/action-diff-triggers@0d193029efd26c76aeacaa84aba3328de8198370 # v0.2.0
      with:
        triggers: ${{ inputs.triggers }}
        diff_branch: ${{ inputs.diff_branch }}

    # Check if a build is required (steps.build.outputs.triggered=true|false)
    - name: Check for builds
      env:
        URL_FALLBACK: ghcr.io/${{ steps.vars.outputs.image_path }}:${{ inputs.tag_fallback }}
      id: build
      shell: bash
      run: |
        # Check for builds
        triggered=true
        if [ "${{ steps.diff.outputs.triggered }}" == "true" ]; then
          echo "Build triggered. Used bcgov/action-diff-triggers."
        elif [ "${{ inputs.repository }}" != "${{ github.repository }}" ]; then
          echo "Build triggered.  Override repository provided."
        elif [ -z "${{ inputs.tag_fallback }}" ]; then
          echo "Build triggered.  No tag_fallback provided."
        elif [[ ! $(docker manifest inspect "${URL_FALLBACK}") ]]; then
          echo "Build triggered.  Fallback tag (tag_fallback) not usable."
        else
          echo "Container build not required"
          triggered=false
        fi
        echo "triggered=$triggered" >> $GITHUB_OUTPUT

    # If a build is not required, reuse a previous image
    - name: Recycle/retag Previous Images
      uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa # v4
      if: steps.build.outputs.triggered != 'true'
      with:
        registry: ghcr.io
        repository: ${{ steps.vars.outputs.image_path }}
        target: ${{ inputs.tag_fallback }}
        tags: |
          ${{ inputs.tags }}

    - uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}

    - name: Set up Docker Buildx
      if: steps.build.outputs.triggered == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      if: steps.build.outputs.triggered == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Prepare Container Metadata tags
      id: meta
      if: steps.build.outputs.triggered == 'true'
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
      with:
        images: ghcr.io/${{ steps.vars.outputs.image_path }}
        tags: ${{ steps.vars.outputs.metadata_tags }}

    - name: Build and push ${{ inputs.package }} Docker image
      id: build_and_push
      if: steps.build.outputs.triggered == 'true'
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.build_context || inputs.package }}
        file: ${{ inputs.build_file || format('{0}/Dockerfile', inputs.package) }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build_args }}
        secrets: ${{ inputs.secrets }}

    - name: Install Syft
      if: steps.build.outputs.triggered == 'true' && inputs.sbom == 'true'
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      id: sbom
      if: steps.build.outputs.triggered == 'true' && inputs.sbom == 'true'
      continue-on-error: true
      shell: bash
      run: |
        set -uo  # Don't exit on error, we handle them explicitly

        # Generate SBOM in both cyclonedx and spdx formats
        IMAGE="ghcr.io/${{ steps.vars.outputs.image_path }}@${{ steps.build_and_push.outputs.digest }}"

        # Sanitize package name for file paths (handle nested paths like airbyte/airbyte-web)
        PACKAGE_SANITIZED=$(echo "${{ inputs.package }}" | tr '/' '-')

        # Create SBOMs directory structure
        mkdir -p sboms

        SBOM_ERROR=false
        PERMISSION_ERROR=false

        # Check if we can access the image (permissions check)
        if ! docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
          PERMISSION_ERROR=true
          echo "::warning::Cannot access image $IMAGE. This may be due to insufficient registry permissions or the image not being available yet. SBOM generation will be skipped."
        else
          # Generate CycloneDX SBOM
          CYCLONEDX_FILE="sboms/${PACKAGE_SANITIZED}-cyclonedx.json"
          SYFT_OUTPUT=$(syft scan "$IMAGE" -o cyclonedx-json 2>&1)
          if [ $? -eq 0 ]; then
            echo "$SYFT_OUTPUT" > "$CYCLONEDX_FILE"
            echo "✓ CycloneDX SBOM generated successfully"
          else
            SBOM_ERROR=true
            if echo "$SYFT_OUTPUT" | grep -qi "permission\|unauthorized\|access denied\|forbidden"; then
              PERMISSION_ERROR=true
              echo "::warning::CycloneDX SBOM generation failed due to image access issues: $SYFT_OUTPUT"
            else
              echo "::warning::CycloneDX SBOM generation failed: $SYFT_OUTPUT"
            fi
            rm -f "$CYCLONEDX_FILE"
          fi
          
          # Generate SPDX SBOM
          SPDX_FILE="sboms/${PACKAGE_SANITIZED}-spdx.json"
          SYFT_OUTPUT=$(syft scan "$IMAGE" -o spdx-json 2>&1)
          if [ $? -eq 0 ]; then
            echo "$SYFT_OUTPUT" > "$SPDX_FILE"
            echo "✓ SPDX SBOM generated successfully"
          else
            SBOM_ERROR=true
            if echo "$SYFT_OUTPUT" | grep -qi "permission\|unauthorized\|access denied\|forbidden"; then
              PERMISSION_ERROR=true
              echo "::warning::SPDX SBOM generation failed due to image access issues: $SYFT_OUTPUT"
            else
              echo "::warning::SPDX SBOM generation failed: $SYFT_OUTPUT"
            fi
            rm -f "$SPDX_FILE"
          fi
        fi

        # Set output flags for downstream steps
        if [ "$PERMISSION_ERROR" = "true" ]; then
          echo "sbom_permission_error=true" >> $GITHUB_OUTPUT
        fi
        if [ "$SBOM_ERROR" = "true" ]; then
          echo "sbom_error=true" >> $GITHUB_OUTPUT
        fi

        # Check if any SBOM files were created
        if [ -n "$(find sboms -name '*.json' -type f 2>/dev/null)" ]; then
          echo "sbom_files_exist=true" >> $GITHUB_OUTPUT
        else
          echo "sbom_files_exist=false" >> $GITHUB_OUTPUT
          if [ "$PERMISSION_ERROR" = "true" ]; then
            echo "::warning::SBOM generation skipped due to image access issues. Workflow will continue without SBOM artifacts."
          else
            echo "::warning::No SBOM files were generated. Workflow will continue without SBOM artifacts."
          fi
        fi

    - name: Upload SBOMs
      uses: actions/upload-artifact@v5
      if: steps.build.outputs.triggered == 'true' && inputs.sbom == 'true'
      continue-on-error: true
      with:
        name: sboms-${{ inputs.package }}-${{ steps.vars.outputs.first_tag }}
        path: sboms/
        if-no-files-found: warn

    - name: Attestation
      continue-on-error: true
      id: attestation
      if: steps.build.outputs.triggered == 'true'
      uses: actions/attest@v3.0.0
      with:
        subject-name: ghcr.io/${{ github.event.repository.name }}/${{ inputs.package }}
        subject-digest: ${{ steps.build_and_push.outputs.digest }}
        predicate-type: "https://in-toto.io/attestation/release/v0.1"
        predicate: '{"purl":"pkg:oci/${{ github.event.repository.name }}/${{ inputs.package }}"}'

    - name: Prompt user to fix permissions
      if: steps.attestation.outcome == 'failure'
      shell: bash
      run: |
        echo "::warning::Attestation skipped due to missing id-token:write and attestations:write permissions. Please update workflow permissions."

    # Action repo needs to be present for cleanup/tests
    - name: Checkout local repo to make sure action.yml is present
      if: github.repository != inputs.repository || failure()
      uses: actions/checkout@v5

    - name: Print summary outputs
      if: always() # Always run this step to summarize the build
      shell: bash
      run: |
        echo "---- Build Summary ----"
        echo "digest: ${{ steps.build_and_push.outputs.digest }}"
        echo "triggered: ${{ steps.diff.outputs.triggered }}"
        echo "tags: ${{ steps.meta.outputs.tags }}"
        echo "-----------------------"
